//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenUtau.Plugin.Builtin.Data {
    using System;
    
    
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenUtau.Plugin.Builtin.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] arpasing_template {
            get {
                object obj = ResourceManager.GetObject("arpasing_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] de_vccv_template {
            get {
                object obj = ResourceManager.GetObject("de_vccv_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] en_c_pv_template {
            get {
                object obj = ResourceManager.GetObject("en_c_pv_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] en_xsampa_template {
            get {
                object obj = ResourceManager.GetObject("en_xsampa_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] envccv_template {
            get {
                object obj = ResourceManager.GetObject("envccv_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] filipino_template {
            get {
                object obj = ResourceManager.GetObject("filipino_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] german_template {
            get {
                object obj = ResourceManager.GetObject("german_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kocv_template {
            get {
                object obj = ResourceManager.GetObject("kocv_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] njokis_template {
            get {
                object obj = ResourceManager.GetObject("njokis_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
