//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenUtau.Core.G2p.Data {
    using System;
    
    
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenUtau.Core.G2p.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] g2p_arpabet {
            get {
                object obj = ResourceManager.GetObject("g2p-arpabet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_arpabet_plus {
            get {
                object obj = ResourceManager.GetObject("g2p_arpabet_plus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_de {
            get {
                object obj = ResourceManager.GetObject("g2p-de", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_de_marzipan {
            get {
                object obj = ResourceManager.GetObject("g2p-de-marzipan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_es {
            get {
                object obj = ResourceManager.GetObject("g2p-es", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_fil {
            get {
                object obj = ResourceManager.GetObject("g2p-fil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_fr {
            get {
                object obj = ResourceManager.GetObject("g2p-fr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_fr_millefeuille {
            get {
                object obj = ResourceManager.GetObject("g2p-fr-millefeuille", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_it {
            get {
                object obj = ResourceManager.GetObject("g2p-it", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_ja_mono {
            get {
                object obj = ResourceManager.GetObject("g2p-ja-mono", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_ko {
            get {
                object obj = ResourceManager.GetObject("g2p-ko", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_pt {
            get {
                object obj = ResourceManager.GetObject("g2p-pt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_ru {
            get {
                object obj = ResourceManager.GetObject("g2p-ru", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] g2p_th {
            get {
                object obj = ResourceManager.GetObject("g2p-th", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] g2p_uk {
            get {
                object obj = ResourceManager.GetObject("g2p-uk", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
